spring:
  application:
    name: Config-Server
  profiles:
    active: native

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/