spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: User-Service
            uri: lb://User-Service
            predicates:
              - Path=/api/v1/user/**
          - id: Payment-Service
            uri: lb://Payment-Service
            predicates:
              - Path=/api/v1/payment/**

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/